version: '3.8'

services:
  fitnab:
    image: ghcr.io/roormonger/fitnab:latest
    container_name: fitnab
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=info,fitnab=debug
